#!/usr/bin/env perl

use Test::Fixture::DBIC::Schema;
use Artemis::Schema::TestTools;

construct_fixture( schema  => testrundb_schema, fixture => 't/fixtures/testrundb/testrun_with_scheduling_run1.yml' );
construct_fixture( schema  => hardwaredb_schema, fixture => 't/fixtures/hardwaredb/systems.yml' );

system(qq(artemis-testrun new --precondition=1 --queue=Kernel --auto_rerun));
system(qq(artemis-testrun new --precondition=2 --queue=KVM    --auto_rerun));
system(qq(artemis-testrun new --precondition=3 --queue=Xen    --auto_rerun));
